export const SEARCH_MAP_ON_PLACE_CHANGED = 'SEARCH_MAP_ON_PLACE_CHANGED';
export const SEARCH_MAP_ON_VIEW_CLICKED = 'SEARCH_MAP_ON_VIEW_CLICKED';
export const SEARCH_MAP_ON_DELETE_CLICKED = 'SEARCH_MAP_ON_DELETE_CLICKED';
